version: '2'
services:
  tp_nginx:
    container_name: ${PREFIX_NAME}_nginx
    build: ./nginx
    ports:
      - "${PORT}:80"
      - "${PORT_SSL}:443"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - ${PATH_TO_PROJECT}:/project
    depends_on:
      - tp_php

  tp_php:
    container_name: ${PREFIX_NAME}_php
    build: ./php
    ports:
      - "9001:9001"
    env_file:
      - ./app.env
      - ./php.env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: tp_mysql
      DB_PORT: 3306

      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./php/conf/php.ini:/usr/local/etc/php/php/conf.d/php.ini
      - ${PATH_TO_PROJECT}:/project
    depends_on:
      - tp_mysql

  tp_mysql:
    container_name: ${PREFIX_NAME}_mysql
    build: ./mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./mysql/data:/var/lib/mysql

  tp_memcached:
    container_name: ${PREFIX_NAME}_memcached
    image: memcached:alpine
    ports:
      - "${MEMCACHED_PORT}:11211"

  tp_redis:
    container_name: ${PREFIX_NAME}_redis
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"

  tp_mongodb:
    container_name: ${PREFIX_NAME}_mongodb
    image: mongo:latest
    ports:
      - "${MONGODB_PORT}:27017"

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    container_name: ${PREFIX_NAME}_phpmyadmin
#    restart: always
#    environment:
#      PMA_ARBITRARY: 1
#      PMA_HOST: tp_mysql
#      PMA_USER: ${DB_USERNAME}
#      PMA_PASSWORD: ${DB_PASSWORD}
#    ports:
#      - "8080:8080"
#    links:
#      - tp_mysql

